# Generated by Django 6.0.6 on 2026-07-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
