# Generated by Django 6.0.6 on 2026-07-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PORTFOLIO', 'Portfolio'), ('BUSINESS', 'Business'), ('BLOG', 'Blog'), ('SAAS', 'SaaS'), ('AGENCY', 'Agency'), ('ECOMMERCE', 'E-Commerce'), ('DOCS', 'Documentation')], max_length=20)),
                ('tech_stack', models.CharField(default='React + Tailwind', max_length=100)),
                ('preview_url', models.URLField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
